services:
    traefik:
        image: "traefik:v2.9"
        restart: unless-stopped
        command:
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
            # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
            - "--certificatesresolvers.myresolver.acme.email=aurorahHarmony@gmail.com"
            - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "letsencrypt:/letsencrypt"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        networks:
            - app-network

    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.site.rule=Host(`localhost`)"
            - "traefik.http.services.site.loadbalancer.server.port=80"
            - "traefik.http.routers.site.entrypoints=websecure"
            - "traefik.http.routers.site.tls.certresolver=myresolver"
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
            - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
            - "traefik.http.routers.redirs.entrypoints=web"
            - "traefik.http.routers.redirs.middlewares=redirect-to-https"
        environment:
            - EVENT_DISABLED_OVERRIDE=0
            - APP_KEY
            - APP_NAME=Egg Hunt
            - APP_ENV=production
            - APP_DEBUG=false
            - APP_URL=http://localhost:80
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_DATABASE=egghunt
            - DB_USERNAME=egghunt
            - DB_PASSWORD=apassword
        # volumes:
            # - ".:/var/www/html"
        networks:
            - app-network

    db:
        image: mariadb
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=egghunt
            - MYSQL_USER=egghunt
            - MYSQL_PASSWORD=apassword
            - MYSQL_ROOT_PASSWORD=myrootpassword
        networks:
            - app-network
        volumes:
            - "database:/var/lib/mysql"
networks:
    app-network:
        driver: bridge

volumes:
    database:
    letsencrypt:

